# Generated by Django 3.2.3 on 2021-05-20 07:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picked',
            field=models.ManyToManyField(related_name='pick', to=settings.AUTH_USER_MODEL),
        ),
    ]
